name: Deploy to WordPress.org
on:
    push:
        tags:
            - "*"
jobs:
    tag:
        name: Upload Plugin to WP SVN
        runs-on: ubuntu-20.04
        strategy:
          fail-fast: true
          matrix:
            php-versions: [ "7.4", "8.0", "8.1" ]
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v2
            -   name: Install dependencies
                uses: php-actions/composer@v6
                with:
                    php_version: "${{ matrix.php-versions }}"
                    dev: no
                    version: 2.x
            -   name: Install npm dependencies
                run: |
                    curl -sS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
                    echo "deb https://deb.nodesource.com/node_16.x focal main" | sudo tee /etc/apt/sources.list.d/nodesource.list
                    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
                    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
                    sudo apt update && sudo apt install nodejs node-gyp libssl1.0-dev yarn
                    yarn --version
                    yarn && yarn run build
                    rm -rf node_modules
            -   name: Upload Action Artifact
                uses: actions/upload-artifact@v1
                with:
                    name: uploadcare-wp
                    path: .
            -   name: WordPress Plugin Deploy
                uses: 10up/action-wordpress-plugin-deploy@98923950204e68db278a958aa8b71e3b07904140
                env:
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SLUG: uploadcare
